apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: learning-lab
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - services.yaml
  - analysis.yaml
  - rollout.yaml
