<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import TopologyDialog from './components/TopologyDialog.vue'
import KubeIcon from './components/KubeIcon.vue'
import { parseOverview, type Health, type Overview, type ResourceModel, type ResourceType } from './domain'
import { buildModels } from './models'

const overview=ref<Overview|null>(null),models=ref<readonly ResourceModel[]>([]),selected=ref<ResourceModel|null>(null),loading=ref(false),error=ref(''),query=ref(''),namespace=ref('all'),health=ref<'all'|Health>('all'),view=ref<'all'|ResourceType>('all'),advanced=ref(false),autoRefresh=ref(true),toast=ref('')
let timer:number|undefined
const namespaces=computed(()=>[...new Set(models.value.map(model=>model.namespace))].sort())
const filtered=computed(()=>{const q=query.value.toLowerCase();return models.value.filter(model=>(view.value==='all'||model.type===view.value)&&(namespace.value==='all'||model.namespace===namespace.value)&&(health.value==='all'||model.health===health.value)&&(!q||[model.name,model.namespace,model.image,model.kind].some(value=>value.toLowerCase().includes(q)))).sort((a,b)=>({degraded:0,progressing:1,healthy:2}[a.health]-{degraded:0,progressing:1,healthy:2}[b.health]||a.name.localeCompare(b.name)))})
const counts=computed(()=>({applications:models.value.filter(x=>x.type==='application'),rollouts:models.value.filter(x=>x.type==='rollout'),deployments:models.value.filter(x=>x.type==='deployment')}))
const applicationGroups=computed(()=>counts.value.applications.map(application=>({application,delivery:models.value.filter(model=>model.type!=='application'&&(model.application===application.name||(!model.application&&model.name===application.name)))})))
const visibleApplications=computed(()=>{const q=query.value.toLowerCase();return applicationGroups.value.filter(group=>!q||[group.application,...group.delivery].some(model=>[model.name,model.image,model.namespace].some(value=>value.toLowerCase().includes(q))))})
const deliverySummary=computed(()=>({healthy:applicationGroups.value.filter(group=>group.application.health==='healthy'&&group.delivery.every(item=>item.health==='healthy')).length,progressing:applicationGroups.value.filter(group=>group.application.health==='progressing'||group.delivery.some(item=>item.health==='progressing')).length,paused:applicationGroups.value.flatMap(group=>group.delivery).filter(item=>item.paused).length}))
const issues=computed(()=>applicationGroups.value.flatMap(group=>[group.application,...group.delivery]).filter(model=>model.health==='degraded'||model.paused))
async function load():Promise<void>{if(loading.value)return;loading.value=true;try{const response=await fetch('/api/overview',{cache:'no-store'});if(!response.ok)throw new Error(`Cluster returned HTTP ${response.status}`);const payload:unknown=await response.json();const parsed=parseOverview(payload);overview.value=parsed;models.value=buildModels(parsed);error.value=''}catch(cause:unknown){error.value=cause instanceof Error?cause.message:'Unable to read cluster state'}finally{loading.value=false}}
async function action(actionName:'sync'|'promote'|'abort',model:ResourceModel):Promise<void>{if(actionName==='abort'&&!window.confirm(`Abort rollout ${model.name}?`))return;try{const group=model.type==='application'?'applications':'rollouts',response=await fetch(`/api/${group}/${encodeURIComponent(model.namespace)}/${encodeURIComponent(model.name)}/${actionName}`,{method:'POST'});if(!response.ok)throw new Error(`Action returned HTTP ${response.status}`);showToast(`${actionName} accepted for ${model.name}`);window.setTimeout(()=>void load(),500)}catch(cause:unknown){showToast(cause instanceof Error?cause.message:'Action failed')}}
function showToast(message:string):void{toast.value=message;window.setTimeout(()=>{toast.value=''},3000)}
function age(timestamp:string):string{if(!timestamp)return'—';const seconds=Math.max(0,(Date.now()-new Date(timestamp).getTime())/1000);if(seconds<60)return`${Math.floor(seconds)}s`;if(seconds<3600)return`${Math.floor(seconds/60)}m`;if(seconds<86400)return`${Math.floor(seconds/3600)}h`;return`${Math.floor(seconds/86400)}d`}
function short(value:string):string{return value.length>15?`${value.slice(0,12)}…`:value}
function kindClass(kind:string):string{return kind.replace(/([a-z])([A-Z])/g,'$1-$2').replace('/','-').toLowerCase()}
onMounted(()=>{void load();timer=window.setInterval(()=>{if(autoRefresh.value&&!document.hidden)void load()},5000)});onBeforeUnmount(()=>window.clearInterval(timer))
</script>

<template>
  <header class="navbar topbar"><div class="brand"><span>F</span><strong>Flightdeck</strong></div><div class="cluster"><i :class="['status','status-xs',error?'status-neutral':'status-success']" /> <strong>learning-lab</strong><span>kind-learning-lab</span></div><div class="updated">{{ overview ? `Updated ${new Date(overview.generatedAt).toLocaleTimeString()}` : 'Connecting…' }}<button class="btn btn-ghost btn-sm btn-square" :disabled="loading" @click="load">↻</button></div></header>
  <aside class="sidebar"><nav><ul class="menu menu-sm"><li><button :class="{active:!advanced}" @click="advanced=false">▦ <span>Applications</span><b class="badge badge-neutral badge-xs">{{ counts.applications.length }}</b></button></li><li><button :class="{active:advanced}" @click="advanced=true">⚙ <span>Advanced resources</span><b class="badge badge-neutral badge-xs">{{ models.length }}</b></button></li></ul></nav><footer><label>Auto refresh <input v-model="autoRefresh" type="checkbox" class="toggle toggle-primary toggle-xs"></label><small>Every 5 seconds</small></footer></aside>
  <main><div class="breadcrumb">Clusters / learning-lab / Applications</div><div class="page-heading"><div><h1>{{ advanced?'Advanced resources':'Applications' }}</h1><p>{{ advanced?'Raw Kubernetes controllers across the cluster.':'Delivery state grouped by Argo CD application.' }}</p></div><div class="page-actions"><label>Advanced <input v-model="advanced" type="checkbox" class="toggle toggle-primary toggle-sm"></label><span class="live-state"><i :class="['status','status-xs',error?'status-error':'status-success']" />{{ error?'Cluster unavailable':'Live' }}</span></div></div>
    <section class="stats metrics"><article class="stat"><span class="stat-title">Applications</span><strong class="stat-value">{{ counts.applications.length }}</strong><small class="stat-desc">Declared in Argo CD</small></article><article class="stat"><span class="stat-title">Healthy</span><strong class="stat-value stat-success">{{ deliverySummary.healthy }}</strong><small class="stat-desc">Application and delivery healthy</small></article><article class="stat"><span class="stat-title">Progressing</span><strong class="stat-value">{{ deliverySummary.progressing }}</strong><small class="stat-desc">Reconciling or rolling out</small></article><article class="stat"><span class="stat-title">Awaiting action</span><strong class="stat-value">{{ deliverySummary.paused }}</strong><small class="stat-desc">Paused for promotion</small></article></section>
    <section v-if="issues.length" class="card card-border issues"><header>Requires attention <span class="badge badge-warning badge-sm">{{ issues.length }} resources</span></header><ul class="list"><li v-for="item in issues" :key="item.id" class="list-row"><span :class="['status',item.health==='degraded'?'status-error':'status-warning']" /><div><strong>{{ item.name }}</strong><small>{{ item.namespace }} · {{ item.kind }}</small></div><span :class="['badge','badge-sm',item.health==='degraded'?'badge-error':'badge-warning']">{{ item.status }}</span></li></ul></section>
    <div v-if="error" class="alert alert-error error" role="alert">{{ error }}</div>
    <section v-if="!advanced" class="card card-border application-panel"><header><div><h2>Delivery applications</h2><span>{{ visibleApplications.length }} applications</span></div><label class="input input-bordered input-sm app-search"><span>⌕</span><input v-model="query" type="search" placeholder="Filter applications"></label></header><div class="application-grid-head"><span>Application</span><span>Source</span><span>Delivery</span><span>Current state</span><span>Actions</span></div><ul class="list application-list"><li v-for="group in visibleApplications" :key="group.application.id" class="application-row"><div class="application-identity"><button class="application-icon kind-application" @click="selected=group.application"><KubeIcon kind="Application" /></button><div><button class="application-name" @click="selected=group.application">{{ group.application.name }}</button><small>{{ group.application.target }}</small></div></div><div class="source-cell"><strong>{{ short(group.application.revision) }}</strong><small :title="group.application.image">{{ group.application.image }}</small></div><div class="delivery-cell"><article v-for="unit in group.delivery" :key="unit.id"><div :class="['delivery-icon',`kind-${kindClass(unit.type==='rollout'?'Rollout':'Deployment')}`]"><KubeIcon :kind="unit.type==='rollout'?'Rollout':'Deployment'" /></div><div><strong>{{ unit.name }}</strong><small>{{ unit.kind }} · {{ unit.ready }} ready</small></div><span v-if="unit.paused" class="badge badge-warning badge-sm">Promote</span><progress v-else :class="['progress',unit.health==='healthy'?'progress-success':unit.health==='degraded'?'progress-error':'progress-warning']" :value="unit.percent" max="100" /></article><p v-if="!group.delivery.length">No delivery controller</p></div><div class="state-cell"><span :class="['status',group.application.health==='healthy'?'status-success':group.application.health==='degraded'?'status-error':'status-warning']" /><div><strong>{{ group.application.status }}</strong><small>{{ group.application.ready }}</small></div></div><div class="application-actions"><button class="btn btn-ghost btn-sm" @click="action('sync',group.application)">Sync</button><button class="btn btn-outline btn-primary btn-sm" @click="selected=group.application">Topology</button></div></li><li v-if="!visibleApplications.length" class="list-row empty">No applications match this filter.</li></ul></section>
    <section v-if="advanced" class="card card-border panel"><header><h2>Resources <span class="badge badge-ghost badge-sm">{{ filtered.length }}</span></h2></header><div class="toolbar"><input v-model="query" class="input input-bordered input-sm" type="search" placeholder="Filter by name, image, or namespace"><select v-model="namespace" class="select select-bordered select-sm"><option value="all">All namespaces</option><option v-for="item in namespaces" :key="item">{{ item }}</option></select><div class="join segments"><button v-for="item in ['all','application','rollout','deployment'] as const" :key="item" :class="['btn','btn-sm','join-item',{active:view===item}]" @click="view=item">{{ item==='all'?'All':`${item}s` }}</button></div><select v-model="health" class="select select-bordered select-sm"><option value="all">All health</option><option value="healthy">Healthy</option><option value="progressing">Progressing</option><option value="degraded">Degraded</option></select></div>
      <div class="table-scroll"><table class="table table-sm"><thead><tr><th>Name</th><th>Kind</th><th>Namespace</th><th>Status</th><th>Ready</th><th>Revision / image</th><th>Age</th><th /></tr></thead><tbody><tr v-for="model in filtered" :key="model.id"><td class="name"><button @click="selected=model">{{ model.name }}</button></td><td><span :class="['badge','badge-sm','kind',`kind-${kindClass(model.kind)}`]"><KubeIcon :kind="model.type==='application'?'Application':model.type==='rollout'?'Rollout':'Deployment'" />{{ model.kind }}</span></td><td>{{ model.namespace }}</td><td><span :class="['health',model.health]"><i :class="['status','status-xs',model.health==='healthy'?'status-success':model.health==='degraded'?'status-error':'status-warning']" />{{ model.status }}</span></td><td class="readiness"><span>{{ model.ready }}</span><i><b :style="{width:`${model.percent}%`}" /></i></td><td><span>{{ short(model.revision) }}</span><small>{{ short(model.image.split('/').at(-1)??model.image) }}</small></td><td>{{ age(model.created) }}</td><td><button class="btn btn-ghost btn-xs more" @click="selected=model">Topology</button></td></tr><tr v-if="!filtered.length"><td colspan="8" class="empty">No resources match the current filters.</td></tr></tbody></table></div><footer>Showing {{ filtered.length }} of {{ models.length }} resources <span>Source: Kubernetes API</span></footer></section>
  </main>
  <TopologyDialog v-if="selected&&overview" :model="selected" :overview="overview" @close="selected=null" @action="action" />
  <div v-if="toast" class="toast">{{ toast }}</div>
</template>
