<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import TopologyDialog from './components/TopologyDialog.vue'
import KubeIcon from './components/KubeIcon.vue'
import { parseOverview, type Health, type Overview, type ResourceModel, type ResourceType } from './domain'
import { buildModels, isPodReady } from './models'

const overview=ref<Overview|null>(null),models=ref<readonly ResourceModel[]>([]),selected=ref<ResourceModel|null>(null),loading=ref(false),error=ref(''),query=ref(''),namespace=ref('all'),health=ref<'all'|Health>('all'),view=ref<'all'|ResourceType>('all'),autoRefresh=ref(true),toast=ref('')
let timer:number|undefined
const namespaces=computed(()=>[...new Set(models.value.map(model=>model.namespace))].sort())
const filtered=computed(()=>{const q=query.value.toLowerCase();return models.value.filter(model=>(view.value==='all'||model.type===view.value)&&(namespace.value==='all'||model.namespace===namespace.value)&&(health.value==='all'||model.health===health.value)&&(!q||[model.name,model.namespace,model.image,model.kind].some(value=>value.toLowerCase().includes(q)))).sort((a,b)=>({degraded:0,progressing:1,healthy:2}[a.health]-{degraded:0,progressing:1,healthy:2}[b.health]||a.name.localeCompare(b.name)))})
const counts=computed(()=>({applications:models.value.filter(x=>x.type==='application'),rollouts:models.value.filter(x=>x.type==='rollout'),deployments:models.value.filter(x=>x.type==='deployment')}))
const podSummary=computed(()=>{const pods=overview.value?.pods??[],ready=pods.filter(isPodReady).length;return{ready,total:pods.length,percent:pods.length?ready/pods.length*100:0}})
const issues=computed(()=>models.value.filter(model=>model.health==='degraded'||model.paused))
async function load():Promise<void>{if(loading.value)return;loading.value=true;try{const response=await fetch('/api/overview',{cache:'no-store'});if(!response.ok)throw new Error(`Cluster returned HTTP ${response.status}`);const payload:unknown=await response.json();const parsed=parseOverview(payload);overview.value=parsed;models.value=buildModels(parsed);error.value=''}catch(cause:unknown){error.value=cause instanceof Error?cause.message:'Unable to read cluster state'}finally{loading.value=false}}
async function action(actionName:'sync'|'promote'|'abort',model:ResourceModel):Promise<void>{if(actionName==='abort'&&!window.confirm(`Abort rollout ${model.name}?`))return;try{const group=model.type==='application'?'applications':'rollouts',response=await fetch(`/api/${group}/${encodeURIComponent(model.namespace)}/${encodeURIComponent(model.name)}/${actionName}`,{method:'POST'});if(!response.ok)throw new Error(`Action returned HTTP ${response.status}`);showToast(`${actionName} accepted for ${model.name}`);window.setTimeout(()=>void load(),500)}catch(cause:unknown){showToast(cause instanceof Error?cause.message:'Action failed')}}
function showToast(message:string):void{toast.value=message;window.setTimeout(()=>{toast.value=''},3000)}
function age(timestamp:string):string{if(!timestamp)return'—';const seconds=Math.max(0,(Date.now()-new Date(timestamp).getTime())/1000);if(seconds<60)return`${Math.floor(seconds)}s`;if(seconds<3600)return`${Math.floor(seconds/60)}m`;if(seconds<86400)return`${Math.floor(seconds/3600)}h`;return`${Math.floor(seconds/86400)}d`}
function short(value:string):string{return value.length>15?`${value.slice(0,12)}…`:value}
function kindClass(kind:string):string{return kind.replace(/([a-z])([A-Z])/g,'$1-$2').replace('/','-').toLowerCase()}
onMounted(()=>{void load();timer=window.setInterval(()=>{if(autoRefresh.value&&!document.hidden)void load()},5000)});onBeforeUnmount(()=>window.clearInterval(timer))
</script>

<template>
  <header class="topbar"><div class="brand"><span>F</span><strong>Flightdeck</strong></div><div class="cluster"><i :class="{online:!error}" /> <strong>learning-lab</strong><span>kind-learning-lab</span></div><div class="updated">{{ overview ? `Updated ${new Date(overview.generatedAt).toLocaleTimeString()}` : 'Connecting…' }}<button :disabled="loading" @click="load">↻</button></div></header>
  <aside class="sidebar"><nav><button :class="{active:view==='all'}" @click="view='all'">▦ <span>Overview</span></button><button :class="{active:view==='application'}" @click="view='application'">◫ <span>Applications</span><b>{{ counts.applications.length }}</b></button><button :class="{active:view==='rollout'}" @click="view='rollout'">⇢ <span>Rollouts</span><b>{{ counts.rollouts.length }}</b></button><button :class="{active:view==='deployment'}" @click="view='deployment'">⬡ <span>Deployments</span><b>{{ counts.deployments.length }}</b></button></nav><footer><label>Auto refresh <input v-model="autoRefresh" type="checkbox" class="toggle toggle-primary toggle-xs"></label><small>Every 5 seconds</small></footer></aside>
  <main><div class="breadcrumb">Clusters / learning-lab / Overview</div><div class="page-heading"><div><h1>Cluster overview</h1><p>Applications and workloads reported by the Kubernetes API.</p></div><span class="live-state"><i :class="{online:!error}" />{{ error?'Cluster unavailable':'Live' }}</span></div>
    <section class="metrics"><article><span>Applications</span><strong>{{ counts.applications.length }}</strong><small>{{ counts.applications.filter(x=>x.health==='healthy').length }} healthy</small></article><article><span>Rollouts</span><strong>{{ counts.rollouts.length }}</strong><small>{{ counts.rollouts.filter(x=>x.paused).length }} paused</small></article><article><span>Deployments</span><strong>{{ counts.deployments.length }}</strong><small>{{ counts.deployments.filter(x=>x.health==='healthy').length }} healthy</small></article><article><span>Pod readiness</span><strong>{{ podSummary.ready }}/{{ podSummary.total }}</strong><small><i class="meter"><b :style="{width:`${podSummary.percent}%`}" /></i>{{ podSummary.total-podSummary.ready }} not ready</small></article></section>
    <section v-if="issues.length" class="issues"><header>Requires attention <span>{{ issues.length }} resources</span></header><div v-for="item in issues" :key="item.id"><span :class="['health',item.health]"><i />{{ item.status }}</span><strong>{{ item.name }}</strong><small>{{ item.namespace }} · {{ item.kind }}</small></div></section>
    <div v-if="error" class="alert alert-error error" role="alert">{{ error }}</div>
    <section class="panel"><header><h2>Resources <span>{{ filtered.length }}</span></h2></header><div class="toolbar"><input v-model="query" class="input input-bordered input-sm" type="search" placeholder="Filter by name, image, or namespace"><select v-model="namespace" class="select select-bordered select-sm"><option value="all">All namespaces</option><option v-for="item in namespaces" :key="item">{{ item }}</option></select><div class="join segments"><button v-for="item in ['all','application','rollout','deployment'] as const" :key="item" :class="['btn','btn-sm','join-item',{active:view===item}]" @click="view=item">{{ item==='all'?'All':`${item}s` }}</button></div><select v-model="health" class="select select-bordered select-sm"><option value="all">All health</option><option value="healthy">Healthy</option><option value="progressing">Progressing</option><option value="degraded">Degraded</option></select></div>
      <div class="table-scroll"><table class="table table-sm"><thead><tr><th>Name</th><th>Kind</th><th>Namespace</th><th>Status</th><th>Ready</th><th>Revision / image</th><th>Age</th><th /></tr></thead><tbody><tr v-for="model in filtered" :key="model.id"><td class="name"><button @click="selected=model">{{ model.name }}</button></td><td><span :class="['badge','badge-sm','kind',`kind-${kindClass(model.kind)}`]"><KubeIcon :kind="model.type==='application'?'Application':model.type==='rollout'?'Rollout':'Deployment'" />{{ model.kind }}</span></td><td>{{ model.namespace }}</td><td><span :class="['health',model.health]"><i />{{ model.status }}</span></td><td class="readiness"><span>{{ model.ready }}</span><i><b :style="{width:`${model.percent}%`}" /></i></td><td><span>{{ short(model.revision) }}</span><small>{{ short(model.image.split('/').at(-1)??model.image) }}</small></td><td>{{ age(model.created) }}</td><td><button class="btn btn-ghost btn-xs more" @click="selected=model">Topology</button></td></tr><tr v-if="!filtered.length"><td colspan="8" class="empty">No resources match the current filters.</td></tr></tbody></table></div><footer>Showing {{ filtered.length }} of {{ models.length }} resources <span>Source: Kubernetes API</span></footer></section>
  </main>
  <TopologyDialog v-if="selected&&overview" :model="selected" :overview="overview" @close="selected=null" @action="action" />
  <div v-if="toast" class="toast">{{ toast }}</div>
</template>
