apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-api-bluegreen
  namespace: argocd
  labels:
    purpose: learning
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_ME/k8s-prod-test.git
    targetRevision: main
    path: k8s/progressive/bluegreen
  destination:
    server: https://kubernetes.default.svc
    namespace: learning-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false

